MovieShopMVC/Models/ErrorViewModel.cs
using System;

namespace MovieShopMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieShopMVC/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MovieShopMVC.Controllers
{
    public class AccountController : Controller
    {
        private readonly IUserService _userService;
        private readonly ICurrentUser _currentUser;

        public AccountController(IUserService userService, ICurrentUser currentUser)
        {
            _userService = userService;
            _currentUser = currentUser;
        }

        // method for registration

        // show the empty view that wil have all the text boxes and submit button
        // localhost/account/register

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterRequestModel model)
        {


            if (!ModelState.IsValid)
            {
                return View();
            }

            // save to DB

            await _userService.RegisterUser(model);
            // redirect to Login

            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserLoginRequestModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = await _userService.Login(model.Email, model.Password);

            if (user == null)
            {
                // wrong password
                ModelState.AddModelError(string.Empty, "Invalid password");
                return View();
            }


            // create cookie claims
            var claims = new List<Claim>
            {
                 new Claim(ClaimTypes.Email, user.Email),
                 new Claim(ClaimTypes.GivenName, user.FirstName),
                 new Claim(ClaimTypes.Surname, user.LastName),
                 new Claim(ClaimTypes.NameIdentifier, user.Id.ToString())
            };

            // identity object
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);


            // HttpContext
            // URL, Http method type, form body, browser, Ip address, 


            // create the cookie
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

            return LocalRedirect("~/");



            // correct pasword
            // display, FirstName, LastName, Email
            // Button/Link Logout
            // Cookie Based Authentication....
            return View();
        }


        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Profile()
        {
            var userId = _currentUser.UserId;
            var userProfileResponse = _userService.GetUserDetails(userId).GetAwaiter().GetResult();
            return View(userProfileResponse);
        }
    }
}

MovieShopMVC/Controllers/CastsController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class CastsController : Controller
    {
        private readonly ICastService _castService;

        public CastsController(ICastService castService)
        {
            _castService = castService;
        }

        public async Task<IActionResult> Index()
        {
            var casts = await _castService.GetResponseCasts();
            return View(casts);
        }

        public async Task<IActionResult> CastDetails(int id)
        {
            var cast = await _castService.GetCastDetailsById(id);

            return View(cast);
        }

        
    }
}

MovieShopMVC/Controllers/HomeController.cs
using ApplicationCore.ServiceInterfaces;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieShopMVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMovieService _movieService;

        public HomeController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        public async Task<IActionResult> Index()
        {
            var movies = await _movieService.GetTopRevenueMovies();
            return View(movies);
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;

        public MoviesController(IMovieService movieSerice)
        {
            _movieService = movieSerice;
        }
        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieService.GetMovieDetails(id);
            
            return View(movie);
        }

    }
}

MovieShopMVC/Views/Casts/CastDetails.cshtml
@model ApplicationCore.Models.CastResponseModel



<div class="container-fluid d-flex justify-content-center">
    <div class="card" style="width: 18rem;">
        <img src="@Model.ProfilePath" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            
            <div class="d-flex justify-content-center">
                <a href="@Model.TmdbUrl" class="btn btn-primary mr-3">Go TMDB</a>
                <a href="javascript:history.go(-1)" class="btn btn-primary">Go Back</a>
            </div>

        </div>
    </div>
</div>

MovieShopMVC/Views/Casts/Index.cshtml
@model List<ApplicationCore.Models.CastResponseModel>;


@foreach (var cast in Model)
{
    <div>
        @cast.Id, @cast.Name, @cast.TmdbUrl
    </div>
}

MovieShopMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Top 30 Revenue";
}

@model List<ApplicationCore.Models.MovieCardResponseModel>


<h2>@ViewData["Title"]</h2>

<div class="rounded">
    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in Model)
            {
                <div class="col-2">
                    <partial name="_MovieCard" model="movie" />
                </div>
            }
        </div>
    </div>
</div>

MovieShopMVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetailsResponseModel

<style>
    #poster {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width:60%
    }
    #section {
        background-image: linear-gradient(rgba(255,255,255,.5), rgba(255,255,255,.5)), url(@Model.BackdropUrl)
    }
    #title {
        text-align:center;
    }
</style>

<section class="container" id="section" >
    <div class="row">

        <div class="col-lg-4">
            <img src="@Model.PosterUrl" id="poster" alt="@Model.Title" />
        </div>
        <div class="col-lg-5">
            <h4 id="title">@Model.Title</h4>
            <span>@Model.Tagline</span> <br />
            <span>@Model.RunTime m | @Model.ReleaseDate.ToString().Substring(5, 5)</span> <br />
            <span>@Model.Rating</span> <br />
            <br />
            <div>
                <p>@Model.Overview</p>
            </div>

        </div>

        <div class="col-3 justify-content-center pt-md-5">
            <div class="mx-auto mb-3">
                <button type="button" class="btn btn-outline-secondary btn-block text-white"><i class="far fa-edit mr-1"></i>REVIEW</button>

            </div>
            <div class="mx-auto mb-3">
                <button type="button" class="btn btn-outline-secondary btn-block text-white"><i class="fas fa-play mr-1"></i>TRAILER</button>

            </div>
            <div class="mx-auto mb-2">

                <button type="button" class="btn btn-light btn-block">BUY 9.90</button>
            </div>
            <div class="mx-auto">

                <button type="button" class="btn btn-light btn-block">WATCH MOVIE</button>
            </div>
        </div>

        <div class="row ">
            <div class="col-5 pr-5">
                <h3>MOVIE FACTS</h3>
                <ul class="list-group">
                    <li class="list-group-item border-left-0 border-right-0 rounded-0 border-bottom-dark">
                        <i class="far fa-calendar-alt mr-2"></i>Release Date
                        <span class="badge badge-secondary">@Model.ReleaseDate.ToString().Substring(0, 10)</span>
                    </li>
                    <li class="list-group-item border-left-0 border-right-0 rounded-0 border-dark">
                        <i class="fas fa-hourglass-half mr-2"></i>Run Time <span class="badge badge-secondary">@Model.RunTime m</span>
                    </li>
                    <li class="list-group-item border-left-0 border-right-0 rounded-0 border-dark">
                        <i class="far fa-money-bill-alt mr-2"></i>Box Office <span class="badge badge-secondary">@Model.Revenue.GetValueOrDefault().ToString("C0")</span>
                    </li>
                    <li class="list-group-item border-left-0 border-right-0 rounded-0 border-dark">
                        <i class="fas fa-dollar-sign mr-2"></i>Budget <span class="badge badge-secondary">@Model.Budget.GetValueOrDefault().ToString("C0")  </span>
                    </li>

                </ul>
                <div class="mt-2">
                    <i class="fab fa-imdb pl-2"></i>
                    <i class="fas fa-sign-out-alt pl-2"></i>
                </div>
            </div>
            <div class="col pl-5">
                <h3>CAST</h3>
                <div>
                    <partial name="_Casts" model="Model.Casts" />
                </div>
            </div>
        </div>

    </div>
</section>

MovieShopMVC/Views/Shared/_Casts.cshtml
@model List<ApplicationCore.Models.CastResponseModel>


@foreach (var cast in Model)
{
    <ul class="list-group">
        <li class="list-group-item d-flex flex-row border-left-0 border-right-0 rounded-0">
            <div class="row w-100 ">
                <div class="col">
                    <a asp-controller="Casts" asp-action="CastDetails" asp-route-id="@cast.Id">
                        <img src="@cast.ProfilePath" alt="cast" class="img-fluid rounded-circle" style="width: 100px" />
                    </a>

                </div>
                <div class="col text-center align-self-center">
                    <span>@cast.Name</span>
                </div>
                <div class="col text-center align-self-center">
                    <span>@cast.Character</span>
                </div>
            </div>



        </li>

    </ul>
}

MovieShopMVC/Views/Shared/_GenreView.cshtml
@using ApplicationCore.ServiceInterfaces

@inject IGenreService _genreService


@foreach (var genre in await _genreService.GetAllGenres())
{
    <a asp-action="genre" asp-controller="Movies" class="dropdown-item" asp-route-id="@genre.Id"> @genre.Name</a>
}

MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Genres
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <partial name="_GenreView" />
                            </div>
                        </li>
                    </ul>
                </div>
            </div>

            <partial name="_LoginPartial" />




        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieCardResponseModel

<div class="card mb-4 shadow bg-light">
    <a asp-controller="Movies" asp-action="Details" asp-route-id ="@Model.Id" >
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title"/>
    </a>
</div>